eureka:
  instance:
     #集群的时候这里不能是一样的
      hostname: dark2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://dark2:1111/eureka/
spring:
  application:
    name: eureka-server
server:
  port: 1112

