eureka:
  instance:
    #集群的时候这里不能是一样的
    hostname: dark1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://dark1:1112/eureka/
spring:
  application:
    name: eureka-server
server:
  port: 1111

